version: '3.8'

services:
  # Baza danych MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adamgolik113
      MYSQL_DATABASE: go2
      MYSQL_USER: root
      MYSQL_PASSWORD: adamgolik113
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  # Aplikacja Go
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: adamgolik113
      DB_NAME: go2
      SECRET_KEY: qzawxsecdrvftbgyhnujimko,1234567890-= # JWT Secret Key
    depends_on:
      - mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge